version: '3.8'
services:
  TramarsaERP:
    build:
      context: ./TramarsaERP
      dockerfile: Dockerfile
    container_name: app-container
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - DATASOURCE_URL=jdbc:postgresql://dpg-crkvvbm8ii6s73et7v1g-a.oregon-postgres.render.com:5432/tramarsa_erp
      - DATASOURCE_USERNAME=tramarsa_erp_user
      - DATASOURCE_PASSWORD=y0bip0mPG2mh70x4fiUTY7vhsIWR9nf7
      - PRIVATE_KEY=alexandersaul26
      - USER_GENERATOR=alexander
